<?php

// ----------------------------
// Snippet: HyperFlexSearchForm
// ----------------------------
// Version: 3r2
// Release: 2007.08.07
// bto@hypernovae.be


// base path
$HyperFlexSearchForm_path_t = $modx->config['base_path'].'assets/snippets/HyperFlexSearchForm/';

// snippet filename
$filename_t = $HyperFlexSearchForm_path_t.'snippet.HyperFlexSearchForm.autogenerated.php';

// if the file doesn't exist yet
if (!file_exists($filename_t))
{
	// trying to retreive the original FlexSearchForm snippet code
	$snippet_tbl_t = $modx->getFullTableName("site_snippets");
	$rs_snippet_i = $modx->dbQuery("SELECT `snippet` FROM ".$snippet_tbl_t." WHERE `name`='FlexSearchForm';");
	// if no error occurred
	if ($rs_snippet_i !== false) {
		$row_snippet_at = $modx->fetchRow($rs_snippet_i);
	}
	// snippet content
	$FlexSearchForm_t = $row_snippet_at['snippet'];
	
	// if no content could be found
	if (empty($FlexSearchForm_t)) {
		// original FlexSearchForm code
		$FlexSearchForm_t = file_get_contents($HyperFlexSearchForm_path_t."snippet.FlexSearchForm.php");
		// removing PHP entities
		$FlexSearchForm_t = str_replace("<?php", "", $FlexSearchForm_t);
		$FlexSearchForm_t = str_replace("?>", "", $FlexSearchForm_t);
	}
	
	// copyright
	$copyright_t = file_get_contents($HyperFlexSearchForm_path_t."HFSF_copyright.txt");
	
	// loading modules
	$module1_t = file_get_contents($HyperFlexSearchForm_path_t."HFSF_module1.php");
	$module2_t = file_get_contents($HyperFlexSearchForm_path_t."HFSF_module2.php");
	$module3_t = file_get_contents($HyperFlexSearchForm_path_t."HFSF_module3.php");
	$module4_t = file_get_contents($HyperFlexSearchForm_path_t."HFSF_module4.php");
	
	// patterns
	$pattern_at = array();
	$pattern_at[1] = "`(\s*//\s*Styles[^:]+:)`i";
	$pattern_at[2] = "`(\s*\\\$rs\s*=\s*\\\$modx->dbQuery\(\\\$sql\);\s*\\\$limit\s*=\s*\\\$modx->recordCount\(\\\$rs\);)`i";
	$pattern_at[3] = "`(\s*\\\$SearchForm\s*.=\s*'<br />'.\\\$resultPageLinks.\"</p>\".\\\$newline;\s*}\s*//\s*end if grabMax)`i";
	$pattern_at[4] = "`(\\\$SearchForm\s*.=\s*'<a class=\"FSF_resultLink\"[^;]*;[^;]+\\\$SearchFormsrc\['description'\][^;]+;)`i";
	
	// replacements
	$replace_at = array();
	$replace_at[1] = "\n\n".$module1_t."$1";
	$replace_at[2] = "\n\n".$module2_t."$1";
	$replace_at[3] = "\n\n".$module3_t."\n$1";
	$replace_at[4] = "\n\t/* The two following lines have been commented by HyperFlexSearchForm :\n\t$1\n\t*/\n\n".$module4_t."\n";
	
	// adding copyright
	$HyperFlexSearchForm_t = $copyright_t."\n\n";
	
	// including modules
	$HyperFlexSearchForm_t .= preg_replace($pattern_at, $replace_at, $FlexSearchForm_t, 1);
	
	// encoding
	if ($modx->config['modx_charset'] != "UTF-8") {
		$HyperFlexSearchForm_t = utf8_decode($HyperFlexSearchForm_t);
	}
	
	/*	// snippet parameters	$snipParam_at = array();	$snipParam_at['templateSearch'] = "Minimal Template,Minimal Template Copy";	$snipParam_at['templateSearchMode'] = "1";	$snipParam_at['parentSearch'] = "0";	$snipParam_at['parentSearchMode'] = "1";	$snipParam_at['documentgroupSearch'] = "dev";	$snipParam_at['documentgroupSearchMode'] = "1";	$snipParam_at['webgroupSearch'] = "testeur";	$snipParam_at['webgroupSearchMode'] = "1";	$snipParam_at['showResultExtract'] = "1";		// snippet evaluation	return $modx->evalSnippet($HyperFlexSearchForm_t, $snipParam_at);
	*/

	// let's open the file
	if (!$handle = fopen($filename_t, 'a')) {		echo "Error while attempting to create the snippet file. Please check the snippet folder access rights.";		exit;	}	// write the snippet content into the file	if (fwrite($handle, "<?php\n\n".$HyperFlexSearchForm_t."\n\n?>") === FALSE) {		echo "Error while attempting to save snippet ($filename_t).";		exit;	}	// close the file
	fclose($handle);
}

// including the snippet
return require $filename_t;


// eof
?>